input_polygons:
  - datasets: 
      - ./stadiumShp/Terrain.shp
    uniqueid: objid
    lifting: Terrain
    height_field: heightFiel
  - datasets: 
      - ./stadiumShp/Roads.shp
    uniqueid: objid
    lifting: Road
    height_field: heightFiel
  - datasets: 
      - ./stadiumShp/Buildings.shp
    uniqueid: objid
    lifting: Building
    height_field: heightFiel
  - datasets: 
      - ./stadiumShp/Forest.shp
    uniqueid: objid
    lifting: Forest
    height_field: heightFiel
  - datasets: 
      - ./stadiumShp/Separation.shp
    uniqueid: objid
    lifting: Separation
    height_field: heightFiel

lifting_options: 
  Building:
    lod: 1
    floor: true
    inner_walls: true
    triangulate: true
    ground:
      height: percentile-10
      use_LAS_classes:
        - 1
        - 2
    roof:
      height: percentile-90
      use_LAS_classes:
        - 2
  Terrain:
    simplification: 0
    simplification_tinsimp: 0.0
    use_LAS_classes:
      - 2
  Forest:
    simplification: 0
    simplification_tinsimp: 0.0
    use_LAS_classes:
      - 2
  Road:
    simplification: 0
    simplification_tinsimp: 0.0
    use_LAS_classes:
     - 2
  Separation:
    height: percentile-80
    use_LAS_classes:
      - 1
      - 2

input_elevation:
  - datasets:
      - ./stadiumLas/stadiumLas.las
    omit_LAS_classes:
      - 0 # Never classified
    thinning: 0

options:
  building_radius_vertex_elevation: 3.0
  radius_vertex_elevation: 1.0
  threshold_jump_edges: 0.5